name: Delete old workflow runs

on:
  schedule:
  - cron: "0 * * * *"
  push:
    branches:
      - "ci"
jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0 #${{ github.event.inputs.days }}
          keep_minimum_runs: 0 # ${{ github.event.inputs.minimum_runs }}
          # delete_workflow_pattern: ${{ github.event.inputs.delete_workflow_pattern }}
          # delete_workflow_by_state_pattern: disabled_manually
          # delete_run_by_conclusion_pattern: ${{ github.event.inputs.delete_run_by_conclusion_pattern }}
          # dry_run: true